//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeKrekelGroup5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dekrekelEntities : DbContext
    {
        public dekrekelEntities()
            : base("name=dekrekelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<uitlening> uitlening { get; set; }
    }
}
