//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeKrekelGroup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class genre
    {
        public genre()
        {
            this.item = new HashSet<item>();
        }
    
        public int idgenre { get; set; }
        public string beschrijving { get; set; }
        public int type_idtype { get; set; }
    
        public virtual type type { get; set; }
        public virtual ICollection<item> item { get; set; }
    }
}
