//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeKrekelGroup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.uitlening = new HashSet<uitlening>();
        }
    
        public int exemplaar { get; set; }
        public string titel { get; set; }
        public string uitgever { get; set; }
        public string omschrijving { get; set; }
        public string jaar { get; set; }
        public string isbn { get; set; }
        public string auteur { get; set; }
        public string imdb { get; set; }
        public int genre_idgenre { get; set; }
        public int type_idtype { get; set; }
    
        public virtual genre genre { get; set; }
        public virtual type type { get; set; }
        public virtual ICollection<uitlening> uitlening { get; set; }
    }
}
