//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeKrekelGroup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.uitlening = new HashSet<uitlening>();
        }
    
        public int idstudent { get; set; }
        public string voornaam { get; set; }
        public string familienaam { get; set; }
    
        public virtual ICollection<uitlening> uitlening { get; set; }
    }
}
