//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeKrekelGroup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class uitlening
    {
        public int iduitlening { get; set; }
        public System.DateTime datumUit { get; set; }
        public int item_exemplaar { get; set; }
        public int student_idstudent { get; set; }
        public Nullable<System.DateTime> datumIn { get; set; }
    
        public virtual item item { get; set; }
        public virtual student student { get; set; }
    }
}
